package com.example.swissarmyapp;

public class Verses {
    static String[] verseList = {"I can do all things through him who strengthens me.",
            "...you are from God and have overcome them, for he who is in you is greater than he who is in the world",
    "Humble yourselves, therefore, under the mighty hand of God so that at that proper time he may exalt you, casting all your anxieties on him, because he cares for you",
    "But you, take courage! Do not let your hands be weak, for your work shall be rewarded.",
    "Whatever you do, work heartily, as for the Lord and not for men.",
    "Be strong and courageous. Do not fear or be in dread of them, for it is the Lord your God who goes with you. He will not leave you or forsake you.",
    "And let us not grow wear of doing good, for in due season we will reap, if we do not give up.",
    "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not grow weary; they shall walk and not faint.",
    "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.",
    "I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world.",
    "Again Jesus spoke to them, saying, 'I am the light of the world. Whoever follows me will not walk in darkness, but will have the light of life.",
    "...be strong and courageous. Do not be frightened, and do not be dismayed, for the Lord your God is with you wherever you go.",
    "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness",
    "",
    "Come to me, all who labor and are heavy laden, and I will give you rest.",
    "Therefore I tell you, do not be anxious about your life, what you will eat or what you will drink, nor about your body, what you will put on. Is not life more than food, and the body more than clothing?",
    "But seek first the kingdom of God and his righteousness, and all these things will be added to you.",
    "I can do all things through him who strengthens me.",
    "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving, let your requests be made known to God.",
    "The name of the Lord is a strong tower; the righteous man runs into it and is safe.",
    "Whoever pursues righteousness and kindness will find life, righteousness, and honor.",
    "As in water face reflects face, so the heart of man reflects the man.",
    "Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.",
    "The Lord is on my side; I will not fear. What can man do to me?",
    "Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!",
    "The steps of a man are established by the Lord, when delights in his way; though he fall, he shall not be cast headlong, for the Lord upholds his hand.",
    "Rejoice in hope, be patient in tribulation, be constant in prayer.",
    "Do not be conformed to this world, but be transformed by the renewal of your mind, that be testing you may discern what is the will of God, what is good and acceptable and perfect.",
    "May the God of hope fill you with all joy and peace in believing, so tht by the power of the Holy Spirit you may abound in hope.",
    "And we know that for those who love God all things work together for good, for those who are called according to his purpose.",
    "And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus."};
    static String[] referenceList = {"1 Corinthians 15:58", "1 John 4:4", "1 Peter 5:6-7", "2 Chronicles 15:7", "Colossians 3:23",
            "Deuteronomy 31:6", "Galatians 6:9", "Isaiah 40:31", "Isaiah 41:10", "John 16:33", "John 8:12", "Joshua 1:9",
            "Lamentations 3:22-23", "", "Matthew 11:28", "Matthew 6:25", "Matthew 6:33", "Philippians 4:13",
            "Philippians 4:6", "Proverbs 18:10", "Proverbs 21:21", "Proverbs 27:19", "Proverbs 3:5-6", "Psalm 118:6",
            "Psalm 34:8", "Psalm 37:23-24", "Romans 12:12", "Romans 12:2", "Romans 15:13", "Romans 8:28", "Philippians 4:7"};
}
